//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCode.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopPhuKienEntities : DbContext
    {
        public ShopPhuKienEntities()
            : base("name=ShopPhuKienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessTimesCount> AccessTimesCounts { get; set; }
        public virtual DbSet<Decentralization> Decentralizations { get; set; }
        public virtual DbSet<DiscountCode> DiscountCodes { get; set; }
        public virtual DbSet<DiscountCodeDetail> DiscountCodeDetails { get; set; }
        public virtual DbSet<ImportCoupon> ImportCoupons { get; set; }
        public virtual DbSet<ImportCouponDetail> ImportCouponDetails { get; set; }
        public virtual DbSet<ItemCart> ItemCarts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Producer> Producers { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductCategoryParent> ProductCategoryParents { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductViewed> ProductVieweds { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDiscountCode> UserDiscountCodes { get; set; }
        public virtual DbSet<UsersSpin> UsersSpins { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<UsageType> UsageTypes { get; set; }
    
        public virtual int dbo_Message_0406b442_9946_4762_aeb9_4198fac9db65_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_0406b442_9946_4762_aeb9_4198fac9db65_QueueActivationSender");
        }
    
        public virtual int dbo_Message_053c5ccf_bda0_42fa_b7a0_0d577a1dee3b_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_053c5ccf_bda0_42fa_b7a0_0d577a1dee3b_QueueActivationSender");
        }
    
        public virtual int dbo_Message_05d44191_6886_4565_9712_8e5d14182cbc_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_05d44191_6886_4565_9712_8e5d14182cbc_QueueActivationSender");
        }
    
        public virtual int dbo_Message_0736bd27_5a5b_4d56_b4f5_e8734597a1d8_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_0736bd27_5a5b_4d56_b4f5_e8734597a1d8_QueueActivationSender");
        }
    
        public virtual int dbo_Message_13945f61_3544_4699_89cb_a489c607b3e1_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_13945f61_3544_4699_89cb_a489c607b3e1_QueueActivationSender");
        }
    
        public virtual int dbo_Message_142a144e_7383_4890_bc3b_3cc5f9bf04d0_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_142a144e_7383_4890_bc3b_3cc5f9bf04d0_QueueActivationSender");
        }
    
        public virtual int dbo_Message_1edc5001_456d_4cc1_8567_83173dca9bd2_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_1edc5001_456d_4cc1_8567_83173dca9bd2_QueueActivationSender");
        }
    
        public virtual int dbo_Message_245037f9_f495_473c_81d9_f1354c819fac_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_245037f9_f495_473c_81d9_f1354c819fac_QueueActivationSender");
        }
    
        public virtual int dbo_Message_27dc8b25_d940_4bfc_a202_4cf9c0ee739e_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_27dc8b25_d940_4bfc_a202_4cf9c0ee739e_QueueActivationSender");
        }
    
        public virtual int dbo_Message_3315306f_1ebc_4d9e_9ead_53a41e43a9f6_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_3315306f_1ebc_4d9e_9ead_53a41e43a9f6_QueueActivationSender");
        }
    
        public virtual int dbo_Message_39ec1b6b_344d_479a_80b8_785a73d7c96a_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_39ec1b6b_344d_479a_80b8_785a73d7c96a_QueueActivationSender");
        }
    
        public virtual int dbo_Message_40365fcc_54d3_46d5_a3bb_58f7d4dc03e8_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_40365fcc_54d3_46d5_a3bb_58f7d4dc03e8_QueueActivationSender");
        }
    
        public virtual int dbo_Message_49d8e313_ae45_4b53_bb37_c5b94d918504_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_49d8e313_ae45_4b53_bb37_c5b94d918504_QueueActivationSender");
        }
    
        public virtual int dbo_Message_4c6b93c6_78a2_44d7_9708_ca8704634340_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_4c6b93c6_78a2_44d7_9708_ca8704634340_QueueActivationSender");
        }
    
        public virtual int dbo_Message_4c9c230f_6c98_479f_9e0a_a5556c585363_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_4c9c230f_6c98_479f_9e0a_a5556c585363_QueueActivationSender");
        }
    
        public virtual int dbo_Message_52627277_4cd9_4bf0_9f3e_12be436fec33_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_52627277_4cd9_4bf0_9f3e_12be436fec33_QueueActivationSender");
        }
    
        public virtual int dbo_Message_55b604b3_aec4_461b_9b4f_b06ce673cef5_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_55b604b3_aec4_461b_9b4f_b06ce673cef5_QueueActivationSender");
        }
    
        public virtual int dbo_Message_5bf76781_fe1b_4b9d_ac38_2a8f33c10712_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_5bf76781_fe1b_4b9d_ac38_2a8f33c10712_QueueActivationSender");
        }
    
        public virtual int dbo_Message_6afcbe20_d6ad_4b50_8526_edfb4ea8322a_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_6afcbe20_d6ad_4b50_8526_edfb4ea8322a_QueueActivationSender");
        }
    
        public virtual int dbo_Message_73e9de33_c5ec_4028_b234_ccda81f96090_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_73e9de33_c5ec_4028_b234_ccda81f96090_QueueActivationSender");
        }
    
        public virtual int dbo_Message_740bf82c_bd3b_4cf8_8656_0de55207ab59_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_740bf82c_bd3b_4cf8_8656_0de55207ab59_QueueActivationSender");
        }
    
        public virtual int dbo_Message_939ba436_effd_4beb_a5e2_186d4bf851ca_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_939ba436_effd_4beb_a5e2_186d4bf851ca_QueueActivationSender");
        }
    
        public virtual int dbo_Message_a92d24a9_3a9c_46ff_9ff3_86891ea3f459_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_a92d24a9_3a9c_46ff_9ff3_86891ea3f459_QueueActivationSender");
        }
    
        public virtual int dbo_Message_aa76d402_a7fa_4d30_b092_9d2cc3adad9a_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_aa76d402_a7fa_4d30_b092_9d2cc3adad9a_QueueActivationSender");
        }
    
        public virtual int dbo_Message_bb20ff31_f988_4393_8a89_4ea51e477f39_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_bb20ff31_f988_4393_8a89_4ea51e477f39_QueueActivationSender");
        }
    
        public virtual int dbo_Message_bd127a53_09ae_44e8_b69b_c0ee2e86ba1a_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_bd127a53_09ae_44e8_b69b_c0ee2e86ba1a_QueueActivationSender");
        }
    
        public virtual int dbo_Message_cf60b8af_d794_42cc_b662_c91c0f7bee70_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_cf60b8af_d794_42cc_b662_c91c0f7bee70_QueueActivationSender");
        }
    
        public virtual int dbo_Message_fc23723f_9860_44bf_886a_0082a9df516e_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_fc23723f_9860_44bf_886a_0082a9df516e_QueueActivationSender");
        }
    
        public virtual int dbo_Message_fe2a8ed6_2783_4070_8938_2533085b7827_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Message_fe2a8ed6_2783_4070_8938_2533085b7827_QueueActivationSender");
        }
    
        public virtual int dbo_Order_248a5112_d675_4b3b_9809_be67bc8fb1d9_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_248a5112_d675_4b3b_9809_be67bc8fb1d9_QueueActivationSender");
        }
    
        public virtual int dbo_Order_286f8088_9cf0_4335_af0c_c26834496138_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_286f8088_9cf0_4335_af0c_c26834496138_QueueActivationSender");
        }
    
        public virtual int dbo_Order_4321986f_c434_4ee4_9612_8c9edb275393_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_4321986f_c434_4ee4_9612_8c9edb275393_QueueActivationSender");
        }
    
        public virtual int dbo_Order_52861545_c86f_4739_92b4_8fabebcba97f_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_52861545_c86f_4739_92b4_8fabebcba97f_QueueActivationSender");
        }
    
        public virtual int dbo_Order_5d0dac80_6ec1_4cf4_a9ea_5c59bfe59f3b_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_5d0dac80_6ec1_4cf4_a9ea_5c59bfe59f3b_QueueActivationSender");
        }
    
        public virtual int dbo_Order_a6d1740b_bdea_4338_9907_321472b9fd9b_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_a6d1740b_bdea_4338_9907_321472b9fd9b_QueueActivationSender");
        }
    
        public virtual int dbo_Order_b3b3bf91_7bf9_417b_8571_d6dce35b7b5d_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_b3b3bf91_7bf9_417b_8571_d6dce35b7b5d_QueueActivationSender");
        }
    
        public virtual int dbo_Order_d9d45c60_5283_4773_a023_e15a2550ac63_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_d9d45c60_5283_4773_a023_e15a2550ac63_QueueActivationSender");
        }
    
        public virtual int dbo_Order_d9dfc9d1_3b03_4aec_b96b_eb0f0f583fe0_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_d9dfc9d1_3b03_4aec_b96b_eb0f0f583fe0_QueueActivationSender");
        }
    
        public virtual int dbo_Order_e7d70651_d7b8_4536_b24b_b4473ed89789_QueueActivationSender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_Order_e7d70651_d7b8_4536_b24b_b4473ed89789_QueueActivationSender");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
